package com.fation.database.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.fation.database.greendao.TAppUser;
import com.fation.database.greendao.TAppToken;
import com.fation.database.greendao.TAppMvp;

import com.fation.database.greendao.TAppUserDao;
import com.fation.database.greendao.TAppTokenDao;
import com.fation.database.greendao.TAppMvpDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tAppUserDaoConfig;
    private final DaoConfig tAppTokenDaoConfig;
    private final DaoConfig tAppMvpDaoConfig;

    private final TAppUserDao tAppUserDao;
    private final TAppTokenDao tAppTokenDao;
    private final TAppMvpDao tAppMvpDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tAppUserDaoConfig = daoConfigMap.get(TAppUserDao.class).clone();
        tAppUserDaoConfig.initIdentityScope(type);

        tAppTokenDaoConfig = daoConfigMap.get(TAppTokenDao.class).clone();
        tAppTokenDaoConfig.initIdentityScope(type);

        tAppMvpDaoConfig = daoConfigMap.get(TAppMvpDao.class).clone();
        tAppMvpDaoConfig.initIdentityScope(type);

        tAppUserDao = new TAppUserDao(tAppUserDaoConfig, this);
        tAppTokenDao = new TAppTokenDao(tAppTokenDaoConfig, this);
        tAppMvpDao = new TAppMvpDao(tAppMvpDaoConfig, this);

        registerDao(TAppUser.class, tAppUserDao);
        registerDao(TAppToken.class, tAppTokenDao);
        registerDao(TAppMvp.class, tAppMvpDao);
    }
    
    public void clear() {
        tAppUserDaoConfig.getIdentityScope().clear();
        tAppTokenDaoConfig.getIdentityScope().clear();
        tAppMvpDaoConfig.getIdentityScope().clear();
    }

    public TAppUserDao getTAppUserDao() {
        return tAppUserDao;
    }

    public TAppTokenDao getTAppTokenDao() {
        return tAppTokenDao;
    }

    public TAppMvpDao getTAppMvpDao() {
        return tAppMvpDao;
    }

}
