package com.fation.database.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.fation.database.greendao.TAppMvp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table TAPP_MVP.
*/
public class TAppMvpDao extends AbstractDao<TAppMvp, Long> {

    public static final String TABLENAME = "TAPP_MVP";

    /**
     * Properties of entity TAppMvp.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, Integer.class, "title", false, "TITLE");
        public final static Property Address = new Property(2, String.class, "address", false, "ADDRESS");
        public final static Property Bz = new Property(3, Integer.class, "bz", false, "BZ");
        public final static Property Bbh = new Property(4, Integer.class, "bbh", false, "BBH");
        public final static Property Cjsj = new Property(5, java.util.Date.class, "cjsj", false, "CJSJ");
        public final static Property Xgsj = new Property(6, java.util.Date.class, "xgsj", false, "XGSJ");
    };


    public TAppMvpDao(DaoConfig config) {
        super(config);
    }
    
    public TAppMvpDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TAPP_MVP' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'TITLE' INTEGER," + // 1: title
                "'ADDRESS' TEXT," + // 2: address
                "'BZ' INTEGER," + // 3: bz
                "'BBH' INTEGER," + // 4: bbh
                "'CJSJ' INTEGER," + // 5: cjsj
                "'XGSJ' INTEGER);"); // 6: xgsj
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TAPP_MVP'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TAppMvp entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer title = entity.getTitle();
        if (title != null) {
            stmt.bindLong(2, title);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(3, address);
        }
 
        Integer bz = entity.getBz();
        if (bz != null) {
            stmt.bindLong(4, bz);
        }
 
        Integer bbh = entity.getBbh();
        if (bbh != null) {
            stmt.bindLong(5, bbh);
        }
 
        java.util.Date cjsj = entity.getCjsj();
        if (cjsj != null) {
            stmt.bindLong(6, cjsj.getTime());
        }
 
        java.util.Date xgsj = entity.getXgsj();
        if (xgsj != null) {
            stmt.bindLong(7, xgsj.getTime());
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TAppMvp readEntity(Cursor cursor, int offset) {
        TAppMvp entity = new TAppMvp( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // address
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // bz
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // bbh
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)), // cjsj
            cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)) // xgsj
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TAppMvp entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setAddress(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBz(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setBbh(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setCjsj(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
        entity.setXgsj(cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TAppMvp entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TAppMvp entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
