package com.fation.database.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TAPP_MVP.
 */
public class TAppMvp {

    private Long id;
    private Integer title;
    private String address;
    private Integer bz;
    private Integer bbh;
    private java.util.Date cjsj;
    private java.util.Date xgsj;

    public TAppMvp() {
    }

    public TAppMvp(Long id) {
        this.id = id;
    }

    public TAppMvp(Long id, Integer title, String address, Integer bz, Integer bbh, java.util.Date cjsj, java.util.Date xgsj) {
        this.id = id;
        this.title = title;
        this.address = address;
        this.bz = bz;
        this.bbh = bbh;
        this.cjsj = cjsj;
        this.xgsj = xgsj;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getTitle() {
        return title;
    }

    public void setTitle(Integer title) {
        this.title = title;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Integer getBz() {
        return bz;
    }

    public void setBz(Integer bz) {
        this.bz = bz;
    }

    public Integer getBbh() {
        return bbh;
    }

    public void setBbh(Integer bbh) {
        this.bbh = bbh;
    }

    public java.util.Date getCjsj() {
        return cjsj;
    }

    public void setCjsj(java.util.Date cjsj) {
        this.cjsj = cjsj;
    }

    public java.util.Date getXgsj() {
        return xgsj;
    }

    public void setXgsj(java.util.Date xgsj) {
        this.xgsj = xgsj;
    }

}
