package com.fation.database.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TAPP_USER.
 */
public class TAppUser {

    private Long id;
    /** Not-null value. */
    private String xm;
    /** Not-null value. */
    private String zh;
    /** Not-null value. */
    private String mm;
    private Integer xb;
    private java.util.Date csrq;
    private String lxfs;
    private java.util.Date cjsj;
    private java.util.Date xgsj;

    public TAppUser() {
    }

    public TAppUser(Long id) {
        this.id = id;
    }

    public TAppUser(Long id, String xm, String zh, String mm, Integer xb, java.util.Date csrq, String lxfs, java.util.Date cjsj, java.util.Date xgsj) {
        this.id = id;
        this.xm = xm;
        this.zh = zh;
        this.mm = mm;
        this.xb = xb;
        this.csrq = csrq;
        this.lxfs = lxfs;
        this.cjsj = cjsj;
        this.xgsj = xgsj;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getXm() {
        return xm;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setXm(String xm) {
        this.xm = xm;
    }

    /** Not-null value. */
    public String getZh() {
        return zh;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setZh(String zh) {
        this.zh = zh;
    }

    /** Not-null value. */
    public String getMm() {
        return mm;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMm(String mm) {
        this.mm = mm;
    }

    public Integer getXb() {
        return xb;
    }

    public void setXb(Integer xb) {
        this.xb = xb;
    }

    public java.util.Date getCsrq() {
        return csrq;
    }

    public void setCsrq(java.util.Date csrq) {
        this.csrq = csrq;
    }

    public String getLxfs() {
        return lxfs;
    }

    public void setLxfs(String lxfs) {
        this.lxfs = lxfs;
    }

    public java.util.Date getCjsj() {
        return cjsj;
    }

    public void setCjsj(java.util.Date cjsj) {
        this.cjsj = cjsj;
    }

    public java.util.Date getXgsj() {
        return xgsj;
    }

    public void setXgsj(java.util.Date xgsj) {
        this.xgsj = xgsj;
    }

}
