package com.fation.database.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TAPP_TOKEN.
 */
public class TAppToken {

    private Long id;
    private String token;
    private String zh;
    private String zt;
    private java.util.Date cjsj;
    private java.util.Date xgsj;

    public TAppToken() {
    }

    public TAppToken(Long id) {
        this.id = id;
    }

    public TAppToken(Long id, String token, String zh, String zt, java.util.Date cjsj, java.util.Date xgsj) {
        this.id = id;
        this.token = token;
        this.zh = zh;
        this.zt = zt;
        this.cjsj = cjsj;
        this.xgsj = xgsj;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getZh() {
        return zh;
    }

    public void setZh(String zh) {
        this.zh = zh;
    }

    public String getZt() {
        return zt;
    }

    public void setZt(String zt) {
        this.zt = zt;
    }

    public java.util.Date getCjsj() {
        return cjsj;
    }

    public void setCjsj(java.util.Date cjsj) {
        this.cjsj = cjsj;
    }

    public java.util.Date getXgsj() {
        return xgsj;
    }

    public void setXgsj(java.util.Date xgsj) {
        this.xgsj = xgsj;
    }

}
